name: Deploy Data Eng project on prod

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Job de copie de fichier necessaire sur le serveur scaleway
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload all file in repository to Scaleway
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SCALEWAY_HOST }}
        username: ${{ secrets.SCALEWAY_USER }}
        key: ${{ secrets.SCALEWAY_SSH_KEY }}
        source: "."
        target: '/home/data-enginer'
  #copie du repertoire courant dans le repertoire /home/data-enginer

#deuxieme job pour deployer en production
  deploy:
    runs-on: ubuntu-latest
    needs: copy-files
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SCALEWAY_HOST }}
        username: ${{ secrets.SCALEWAY_USER }}
        key: ${{ secrets.SCALEWAY_SSH_KEY }}
        port: 22
        script: |
          cd /home/data-enginer
          docker-compose down || true
          docker-compose rm -f || true
          docker-compose build 
          chmod 777 ./logs
          chmod 777 ./logs/scheduler
          docker-compose up -d
          toilet FAST MLOPS
          echo 'GOOD JOBS'